/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2023-11-16 02:20:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612850415545L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Agency - Start Bootstrap Theme</title>\r\n");
      out.write("        <!-- Favicon-->\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("    </head>\r\n");
      out.write("    <body id=\"page-top\">\r\n");
      out.write("        <!-- Navigation-->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Masthead(banner)-->\r\n");
      out.write("        <header class=\"masthead\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\t          <div class=\"masthead-subheading\">Welcome To Our Studio!</div>\r\n");
      out.write("\t          <div class=\"masthead-heading text-uppercase\">It's Nice To Meet You</div>\r\n");
      out.write("              <a class=\"btn btn-primary btn-xl text-uppercase\" href=\"#services\">Tell Me More</a>\r\n");
      out.write("\t\t\t  <a class=\"btn btn-primary btn-xs text-uppercase\" href=\"#\" id=\"prevButton\">Previous</a>\r\n");
      out.write("\t\t\t  <a class=\"btn btn-primary btn-xs text-uppercase\" href=\"#\" id=\"nextButton\">Next</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("        <!-- Services-->\r\n");
      out.write("        <section class=\"page-section\" id=\"services\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">Services</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row text-center\">\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <span class=\"fa-stack fa-4x\">\r\n");
      out.write("                            <i class=\"fas fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("                            <i class=\"fas fa-shopping-cart fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <h4 class=\"my-3\">E-Commerce</h4>\r\n");
      out.write("                        <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <span class=\"fa-stack fa-4x\">\r\n");
      out.write("                            <i class=\"fas fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("                            <i class=\"fas fa-laptop fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <h4 class=\"my-3\">Responsive Design</h4>\r\n");
      out.write("                        <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <span class=\"fa-stack fa-4x\">\r\n");
      out.write("                            <i class=\"fas fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("                            <i class=\"fas fa-lock fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <h4 class=\"my-3\">Web Security</h4>\r\n");
      out.write("                        <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Portfolio Grid-->\r\n");
      out.write("        <section class=\"page-section bg-light\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">Portfolio</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                        <!-- Portfolio item 1-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal1\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/1.jpg\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Threads</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Illustration</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                        <!-- Portfolio item 2-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal2\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/2.jpg\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Explore</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Graphic Design</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                        <!-- Portfolio item 3-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal3\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/3.jpg\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Finish</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Identity</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4 mb-lg-0\">\r\n");
      out.write("                        <!-- Portfolio item 4-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal4\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/4.jpg\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Lines</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Branding</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4 mb-sm-0\">\r\n");
      out.write("                        <!-- Portfolio item 5-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal5\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/5.jpg\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Southwest</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Website Design</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                        <!-- Portfolio item 6-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal6\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/6.jpg\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Window</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Photography</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- About-->\r\n");
      out.write("        <section class=\"page-section\" id=\"about\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">About</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"timeline\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/about/1.jpg\" alt=\"...\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>2009-2011</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Our Humble Beginnings</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"timeline-inverted\">\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/about/2.jpg\" alt=\"...\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>March 2011</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">An Agency is Born</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/about/3.jpg\" alt=\"...\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>December 2015</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Transition to Full Service</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"timeline-inverted\">\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/about/4.jpg\" alt=\"...\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>July 2020</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Phase Two Expansion</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"timeline-inverted\">\r\n");
      out.write("                        <div class=\"timeline-image\">\r\n");
      out.write("                            <h4>\r\n");
      out.write("                                Be Part\r\n");
      out.write("                                <br />\r\n");
      out.write("                                Of Our\r\n");
      out.write("                                <br />\r\n");
      out.write("                                Story!\r\n");
      out.write("                            </h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Team-->\r\n");
      out.write("        <section class=\"page-section bg-light\" id=\"team\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">Our Amazing Team</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"team-member\">\r\n");
      out.write("                            <img class=\"mx-auto rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/team/1.jpg\" alt=\"...\" />\r\n");
      out.write("                            <h4>Parveen Anand</h4>\r\n");
      out.write("                            <p class=\"text-muted\">Lead Designer</p>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Parveen Anand Twitter Profile\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Parveen Anand Facebook Profile\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Parveen Anand LinkedIn Profile\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"team-member\">\r\n");
      out.write("                            <img class=\"mx-auto rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/team/2.jpg\" alt=\"...\" />\r\n");
      out.write("                            <h4>Diana Petersen</h4>\r\n");
      out.write("                            <p class=\"text-muted\">Lead Marketer</p>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Diana Petersen Twitter Profile\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Diana Petersen Facebook Profile\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Diana Petersen LinkedIn Profile\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"team-member\">\r\n");
      out.write("                            <img class=\"mx-auto rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/team/3.jpg\" alt=\"...\" />\r\n");
      out.write("                            <h4>Larry Parker</h4>\r\n");
      out.write("                            <p class=\"text-muted\">Lead Developer</p>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Larry Parker Twitter Profile\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Larry Parker Facebook Profile\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Larry Parker LinkedIn Profile\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-8 mx-auto text-center\"><p class=\"large text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Clients-->\r\n");
      out.write("        <div class=\"py-5\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"#!\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logos/microsoft.svg\" alt=\"...\" aria-label=\"Microsoft Logo\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"#!\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logos/google.svg\" alt=\"...\" aria-label=\"Google Logo\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"#!\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logos/facebook.svg\" alt=\"...\" aria-label=\"Facebook Logo\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"#!\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logos/ibm.svg\" alt=\"...\" aria-label=\"IBM Logo\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Contact-->\r\n");
      out.write("        <section class=\"page-section\" id=\"contact\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">Contact Us</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                <!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("                <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                <!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("                <!-- To make this form functional, sign up at-->\r\n");
      out.write("                <!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("                <!-- to get an API token!-->\r\n");
      out.write("                <form id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\r\n");
      out.write("                    <div class=\"row align-items-stretch mb-5\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <!-- Name input-->\r\n");
      out.write("                                <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Your Name *\" data-sb-validations=\"required\" />\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"name:required\">A name is required.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <!-- Email address input-->\r\n");
      out.write("                                <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Your Email *\" data-sb-validations=\"required,email\" />\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"email:required\">An email is required.</div>\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"email:email\">Email is not valid.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group mb-md-0\">\r\n");
      out.write("                                <!-- Phone number input-->\r\n");
      out.write("                                <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"Your Phone *\" data-sb-validations=\"required\" />\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"phone:required\">A phone number is required.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group form-group-textarea mb-md-0\">\r\n");
      out.write("                                <!-- Message input-->\r\n");
      out.write("                                <textarea class=\"form-control\" id=\"message\" placeholder=\"Your Message *\" data-sb-validations=\"required\"></textarea>\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"message:required\">A message is required.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Submit success message-->\r\n");
      out.write("                    <!---->\r\n");
      out.write("                    <!-- This is what your users will see when the form-->\r\n");
      out.write("                    <!-- has successfully submitted-->\r\n");
      out.write("                    <div class=\"d-none\" id=\"submitSuccessMessage\">\r\n");
      out.write("                        <div class=\"text-center text-white mb-3\">\r\n");
      out.write("                            <div class=\"fw-bolder\">Form submission successful!</div>\r\n");
      out.write("                            To activate this form, sign up at\r\n");
      out.write("                            <br />\r\n");
      out.write("                            <a href=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Submit error message-->\r\n");
      out.write("                    <!---->\r\n");
      out.write("                    <!-- This is what your users will see when there is-->\r\n");
      out.write("                    <!-- an error submitting the form-->\r\n");
      out.write("                    <div class=\"d-none\" id=\"submitErrorMessage\"><div class=\"text-center text-danger mb-3\">Error sending message!</div></div>\r\n");
      out.write("                    <!-- Submit Button-->\r\n");
      out.write("                    <div class=\"text-center\"><button class=\"btn btn-primary btn-xl text-uppercase disabled\" id=\"submitButton\" type=\"submit\">Send Message</button></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer py-4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-4 text-lg-start\">Copyright &copy; Your Website 2023</div>\r\n");
      out.write("                    <div class=\"col-lg-4 my-3 my-lg-0\">\r\n");
      out.write("                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Twitter\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Facebook\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"LinkedIn\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 text-lg-end\">\r\n");
      out.write("                        <a class=\"link-dark text-decoration-none me-3\" href=\"#!\">Privacy Policy</a>\r\n");
      out.write("                        <a class=\"link-dark text-decoration-none\" href=\"#!\">Terms of Use</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Portfolio Modals-->\r\n");
      out.write("        <!-- Portfolio item 1 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/1.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Threads\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Illustration\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 2 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/2.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Explore\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Graphic Design\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 3 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/3.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Finish\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Identity\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 4 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/4.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Lines\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Branding\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 5 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/5.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Southwest\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Website Design\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 6 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/portfolio/6.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Window\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Photography\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/scripts.js\"></script>\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <!-- * *                               SB Forms JS                               * *-->\r\n");
      out.write("        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("\t        document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("\t            const masthead = document.querySelector(\"header.masthead\");\r\n");
      out.write("\t            const backgrounds = [\r\n");
      out.write("\t                \"url('https://help.miricanvas.com/hc/article_attachments/900002143783/___________________4_.png')\",\r\n");
      out.write("\t                \"url('https://png.pngtree.com/thumb_back/fw800/background/20190222/ourmid/pngtree-summer-refreshing-banner-background-claritycandycute-backgroundsummer-image_52755.jpg')\", // 두 번째 이미지 경로\r\n");
      out.write("\t                // 여기에 더 많은 이미지 경로를 추가할 수 있습니다.\r\n");
      out.write("\t            ];\r\n");
      out.write("\t            let currentBackgroundIndex = 0;\r\n");
      out.write("\t\r\n");
      out.write("\t            const prevButton = document.getElementById(\"prevButton\");\r\n");
      out.write("\t            const nextButton = document.getElementById(\"nextButton\");\r\n");
      out.write("\t\r\n");
      out.write("\t            function changeBackground() {\r\n");
      out.write("\t                currentBackgroundIndex = (currentBackgroundIndex + 1) % backgrounds.length;\r\n");
      out.write("\t                masthead.style.backgroundImage = backgrounds[currentBackgroundIndex];\r\n");
      out.write("\t            }\r\n");
      out.write("\t\r\n");
      out.write("\t            prevButton.addEventListener(\"click\", function() {\r\n");
      out.write("\t                currentBackgroundIndex = (currentBackgroundIndex - 1 + backgrounds.length) % backgrounds.length;\r\n");
      out.write("\t                masthead.style.backgroundImage = backgrounds[currentBackgroundIndex];\r\n");
      out.write("\t            });\r\n");
      out.write("\t\r\n");
      out.write("\t            nextButton.addEventListener(\"click\", changeBackground);\r\n");
      out.write("\t        });             \r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/main/main.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/views/main/main.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/main.jsp(7,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
